version: 2
updates:
  - package-ecosystem: "conda"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
