channels:
  - defaults
dependencies:
  - python==3.11
  - pip
  - pip:
      - numpy
      - pygame
      - scipy
      - torch
      - psutil
      - numba
      - pretty_midi
      - sounddevice
      - pyaudio
      - matplotlib
      - mkdocs
      - nuitka
      - mkdocs-material
      - mkdocs-git-revision-date-localized-plugin
      - mkdocs-git-authors-plugin
