channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - flake8=7.1.1
  - libffi=3.4.4
  - mccabe=0.7.0
  - openssl=1.1.1w
  - pip=24.2
  - pycodestyle=2.12.1
  - pyflakes=3.2.0
  - python=3.11.0
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024a
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - argparse==1.4.0
      - attrs==24.2.0
      - automat==24.8.1
      - babel==2.16.0
      - buildtools==1.0.6
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - constantly==23.10.4
      - contourpy==1.3.0
      - cycler==0.12.1
      - cython==3.0.11
      - docopt==0.6.2
      - filelock==3.16.1
      - fonttools==4.54.0
      - fsspec==2024.9.0
      - furl==2.1.3
      - ghp-import==2.1.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - greenlet==3.1.1
      - hyperlink==21.0.0
      - idna==3.10
      - incremental==24.7.2
      - jinja2==3.1.4
      - keras==3.5.0
      - kiwisolver==1.4.7
      - llvmlite==0.43.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mergedeep==1.3.4
      - mido==1.3.2
      - mkdocs==1.6.1
      - mkdocs-autorefs==1.2.0
      - mkdocs-get-deps==0.2.0
      - mkdocs-git-authors-plugin==0.9.0
      - mkdocs-git-revision-date-localized-plugin==1.2.9
      - mkdocs-material==9.5.39
      - mkdocs-material-extensions==1.3.1
      - mkdocstrings==0.26.1
      - mpmath==1.3.0
      - networkx==3.3
      - nuitka==2.4.8
      - numba==0.60.0
      - numpy==2.0.2
      - ordered-set==4.1.0
      - orderedmultidict==1.0.1
      - packaging==23.2
      - paginate==0.5.7
      - pathspec==0.12.1
      - pillow==10.4.0
      - platformdirs==4.3.6
      - psutil==6.0.0
      - pyaudio==0.2.14
      - pycparser==2.22
      - pygame==2.6.0
      - pygments==2.18.0
      - pymdown-extensions==10.11.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - python-rtmidi==1.5.8
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyyaml-env-tag==0.1
      - redo==3.0.0
      - regex==2024.9.11
      - requests==2.32.3
      - scipy==1.14.1
      - simplejson==3.19.3
      - six==1.16.0
      - smmap==5.0.1
      - sounddevice==0.5.0
      - sqlalchemy==2.0.35
      - sympy==1.13.3
      - torch==2.4.1
      - torchvision==0.19.1
      - twisted==24.7.0
      - typing-extensions==4.12.2
      - urllib3==2.2.3
      - zope-interface==7.0.3
      - zstandard==0.23.0
