channels:
  - defaults
dependencies:
  - python==3.11
  - pip
  - pip:
      - torch
      - sounddevice
      - pretty_midi
      - scipy
      - matplotlib
      - sympy
      - pygame
      - python-rtmidi
      - psutil
      - numba
