name: ai_synth_env
channels:
  - defaults
dependencies:
  - python==3.11
  - pip:
    - tensorflow
    - sounddevice
    - pretty_midi
    - scipy
    - matplotlib
    - sympy
    - pygame
    - rtmidi
