site_name: Python AI Synthesizer
repo_url: https://github.com/thetechnicker/PythonAISynth
nav:
  - Home: index.md
  - Idea: idea.md
  - Python Modules:
      - Main: python_modules/main.md
      - Graph Canvas V2: python_modules/graph_canvas_v2.md
      - Fourier Neural Network: python_modules/fourier_neural_network.md
      - Fourier Neural Network: python_modules\fourier_neural_network_gui.md
      - Music: python_modules\music.md
      - Predifined Functions: python_modules\predefined_functions.md
      - Simple Input Dialog: python_modules\simple_input_dialog.md
      - STD Redirect: python_modules\std_redirect.md
      - Synth GUI: python_modules\synth_gui.md
      - Utils: python_modules/utils.md

theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      repository: thetechnicker/PythonAISynth
  - git-authors
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
