name: Dayly Build

on:
  push:
    branches:
      - dev

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y portaudio19-dev
      - name: Install dependencies
        run: |
          conda env update --file environment.yml --name base
      - name: Build wheel
        run: |
          conda install wheel
          python setup.py bdist_wheel
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
