name: Pre Release

on:
  push:
    branches:
      - thetechnicker

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
          
      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y portaudio19-dev
          
      - name: Install dependencies
        run: |
          conda env update --file environment.yml --name base
          
      - name: Build wheel
        run: |
          conda install wheel
          python setup.py bdist_wheel
          
      - name: Get version
        id: get_version
        run: echo "VERSION=$(python setup.py --version)" >> $GITHUB_ENV

      - name: List contents of dist folder
        run: |
          ls -la dist/
          
      - name: Upload wheel artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-package
          path: dist/*.whl

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ env.VERSION }}"
          release_name: "Release v${{ env.VERSION }}"
          draft: true
          files: dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

